image: archlinux
secrets:
  - 89991b16-705b-4276-9178-bfc81c7fdd28
environment:
  deploy: nicohman@demenses.net
sources:
  - https://git.sr.ht/~nicohman/nicohman.demenses.net
tasks:
  - deploy: |
      sshopts="ssh -o StrictHostKeyChecking=no"
      $sshopts $deploy /home/nicohman/nicohman.demenses.net/update.sh &
      sshpid=$!
      sleep 10
      kill $sshpid
