title: nicohman
url: "https://nicohman.demenses.net"
baseurl: ""

markdown: kramdown
#ins_logo: "./bits-logo.png"
remote_theme: ankitsultana/researcher@gem

tracking_id: #

footer: yes
footer_url: "https://github.com/ankitsultana"
footer_text: "Original theme design by Ankit Sultana"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "/"
 - name: "Contact"
   link: "contact"
 - name: "Git"
   link: "https://git.sr.ht/~nicohman"
 - name: "Downloads"
   link: "downloads"